[package]
name = "mango_airdrop"
edition = "2024.alpha"
 published-at = "0x023ed92525e77ba87facb33402a111c460255c9e14ec17ef9e134a078d3539df"
 version = "0.0.1"

[dependencies]
MoveStdlib = {local = "../../../../mgo-devnet/move-stdlib" }
Mgo = { local = "../../../../mgo-devnet/mgo-framework" }

[addresses]
mango_airdrop = "0x0"
std = "0x1"
mgo = "0x2"